package com.alimurtaza.android.twoactivitieschallenge;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

public class MainActivity extends AppCompatActivity {

    private static final String passage_title = "First impressions count";
    public static final String EXTRA_PASSAGE =
            "com.alimurtaza.android.twoactivitieschallenge.extra.MESSAGE";
    private static final String passage = "I became interested in studying first impressions after my research group discovered that such impressions can predict the outcomes of important political elections. First impressions mattered.\n" +
            "\n" +
            "I was in my first few years as an assistant professor at Princeton with a tiny lab consisting of one half-time research assistant and two graduate students. There was no easy way to collect data online at the time, so we participated in one of the ‘questionnaire days’ organised by the department of psychology. These Q days were advertised among students on campus, and those willing to trade an hour of their time for $10 or so were handed a thick bundle of different questionnaires to fill out. \n" +
            "\n" +
            "Buried among those were some of our questionnaires presenting pairs of images of the winner and the runner-up from all the United States Senate races for 2000 and 2002, excluding races with highly recognisable politicians such as Hillary Clinton and John Kerry. Different students were assigned to different questions, for example ‘Who looks more competent?’ and ‘Who looks more honest?’ We were hoping that some of these questions would predict who won the elections. When we analysed the data, our hopes were surpassed. Judgments of who appeared more competent predicted about 70 per cent of the elections.\n" +
            "\n" +
            "A general rule of science is that results should be replicated, especially if these results are surprising. So we put everything else on hold and started preparing new questionnaires.\n" +
            "\n" +
            "We ultimately replicated our initial results and eventually wrote up the findings. The paper was published in Science. This spurred a number of replications by different research groups and in different countries. This was not just a US election phenomenon.\n" +
            "\n" +
            "Unexpected findings are typically met with skepticism. Before our findings were published, I applied for funding for this research. The way funding applications work is that you write a research proposal and that proposal is reviewed by anonymous reviewers. The reviews covered the whole range, from the very positive to the very negative. One of the reviewers basically wrote that the kinds of effects we had documented – naive judgments from facial appearance predicting political elections – must occur only in my lab. In their words: ‘Before I would find these proposed studies at all compelling, I would like to see some evidence that this situation occurs anywhere outside of the PI’s laboratory.’ The PI stands for me, the principal investigator. Needless to say, I did not get the funding.\n" +
            "\n" +
            "After the findings were published, I received my first hate email. I still don’t understand what instigated it, but its author was pissed off with our ‘trivial’ results. Buried among the profanities, he actually had a plausible alternative explanation of our findings. According to him, it was patently obvious that the observed effects were due to media exposure. Although our participants did not explicitly recognise the faces of the politicians, they must have been exposed to these faces before, and this exposure made them rate more familiar politicians as more competent. If more familiar politicians are more likely to be the winners, this could explain our results. Though plausible, this hypothesis turned out to be false.\n" +
            "\n" +
            "The right way to question unexpected findings is to conduct replication studies and test alternative explanations. Political scientists were the first to test trivial explanations, such as differences in the pictures’ image quality or in campaign spending. But such differences could not explain the appearance effects on election outcomes, nor could differences in gender and race. In fact, we obtained our best results when the prediction was limited to elections in which the candidates were matched on race and gender. Familiarity with the candidates’ faces could not explain the effects either.\n" +
            "\n" +
            "My favourite replication was a study conducted by John Antonakis and Olaf Dalgas of the University of Lausanne, in which Swiss children’s judgments predicted the outcomes of French parliamentary elections. Some of the kids in the study were not even born when these elections were conducted. In other replications in Europe, judgments of US and Swedish participants predicted the outcomes of Finnish elections. With one of my students and a Bulgarian colleague, we used judgments of Americans to predict the 2011 presidential elections in Bulgaria, the country where I grew up. These elections are interesting because there is a very low threshold for entering the race and, as a result, there are many candidates: 18 in this particular year. It was sad to see one of my professors from Sofia University doing very poorly in terms of both appearance judgments and electoral votes. What makes you a good professor does not necessarily make you a good politician.\n" +
            "\n" +
            "In a final twist, Gabriel Lenz and Chappell Lawson, political scientists at Berkeley and MIT respectively, had American and Indian participants rate the faces of Mexican and Brazilian politicians. Although the cultures of the raters and the politicians were deliberately chosen to be very different, the raters agreed in their judgments of the politicians, and these judgments predicted the outcomes of the elections.But how does this really work in the real world? For one thing, participants in psychology experiments, and certainly kids, are not representative of those who actually vote. For another, it is hard to imagine that political partisans are voting based on the appearance of candidates. What they care about is the political affiliation of these candidates, not their looks.\n" +
            "\n" +
            "Lawson and Lenz have done great research to figure out how it might work in the real world. Studying real voters, they found that appearance affects only those who know next to nothing about politics. Being glued to the TV most of the time makes the effect of appearance even stronger. In other words, appearance has its biggest effects on politics-ignorant couch potatoes. Some of them are the swing or undecided voters.\n" +
            "\n" +
            "Lenz and Lawson’s findings make perfect sense to psychologists. One of the successful metaphors describing the mind is a ‘cognitive miser’. When we need to make a decision, particularly when we have little knowledge, we rely on shortcuts: hunches, ‘gut’ responses, stereotypes. We use shortcuts because it is easy. We are ready to leap to conclusions, especially when we are too lazy or busy to look for hard evidence. And most of us are cognitively lazy or busy some of the time. When it comes to decisions about strangers, the easiest, most accessible shortcut is our first impression. Unknowledgeable voters go for this shortcut.\n" +
            "\n" +
            "Do the effects obtained in contrived lab demonstrations make a difference in the real world? In close races, unknowledgeable or ‘appearance-based’ voters can sway the outcome of the races. Lenz and Lawson estimated that candidates who appear slightly more competent than their opponents can get as much as 5 per cent more votes from unknowledgeable, TV-loving voters. Recently, Lenz and his students conducted experiments with voters in California and 18 other states. In the two weeks before an election day, voters were shown the ballots either with pictures of the candidates or without pictures, and asked to express their intention to vote. Depending on the race – primary or general – when the voters saw the pictures, the best-looking candidates got a boost between 10 per cent and 20 per cent over the appearance-disadvantaged candidates. Lenz estimated that the looks of the candidates could have changed the outcomes of 29 per cent of the races in primary elections and in 14 per cent of the general elections. These results are quite remarkable, because the experimental design rules out the possibility that factors such as candidate effort and spending can explain the effects of appearance. The only difference between the voters in the two experimental conditions was the presence or absence of pictures on the ballot.\n" +
            "\n" +
            "One uninteresting explanation of these results is that, once presented with the candidates’ pictures, the voters find their influence irresistible, and this irresistible, immediate influence inflates the effect of appearance on votes. We should be grateful that ballots in the US, unlike in Brazil, Belgium, Greece and Ireland, do not include pictures of the candidates. But, for all we know, the effect of appearance might have been underestimated. Many of the voters in the no-picture ballot condition knew how the candidates look, and this should have minimised the difference between their choices and the choices of voters in the picture-ballot condition. This is testable. Lenz and colleagues reasoned that as the campaign gets closer to election day, the effect of appearance should increase in the control group, which did not have pictures on the ballots. The reason is that voters should be increasingly likely to be exposed to images of the candidates. This is what Lenz and colleagues found. If anything, the effect of appearance seemed to decrease in the experimental group, which had pictures on the ballot, presumably because voters were finding other information about the candidates that influenced their choices. These secondary analyses suggest that the effects of appearance on votes cannot be completely explained by the fact that the voters in the experimental group saw the candidates’ pictures; and that the actual effects can be even larger than the estimated effects. Another depressing finding was that political knowledge did not inoculate voters against appearance in congressional primaries where multiple candidates from the same party were competing against each other.";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button button = findViewById(R.id.button_one);
        button.setText(passage_title);
    }

    public void sendPassage(View view) {
        Intent intent = new Intent(this, SecondActivity.class);
        intent.putExtra(EXTRA_PASSAGE, passage);
        startActivity(intent);
    }
}
